server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/aimedia
spring.datasource.username=postgres
spring.datasource.password=root

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Upload
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

groq.api.key=${GROQ_API_KEY}

ollama.base-url=http://localhost:11434
ollama.model=phi3

logging.level.org.springframework.ai=DEBUG
